# Generated by Django 5.2.5 on 2025-09-03 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_school_name_alter_department_unique_together'),
        ('instructor_portal', '0002_instructorprofile_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructors', to='core.department'),
        ),
    ]
