# Generated by Django 5.1.1 on 2025-11-14 04:59

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_contactinfo_address_alter_contactinfo_email_and_more'),
        ('instructor_portal', '0003_alter_instructorprofile_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorprofile',
            name='courses_taught',
            field=models.ManyToManyField(blank=True, related_name='instructors', to='core.course'),
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='email',
            field=models.EmailField(default='instructor@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='full_name',
            field=models.CharField(default='Instructor Name', max_length=200),
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='phone',
            field=models.CharField(default='0000000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_pic'),
        ),
    ]
