# Generated by Django 5.2.5 on 2025-08-10 20:57

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_course_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentapplication',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='enrollmentapplication',
            name='disability_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='enrollmentapplication',
            name='disability_status',
            field=models.CharField(choices=[('none', 'None'), ('physical', 'Physical'), ('visual', 'Visual'), ('hearing', 'Hearing'), ('other', 'Other')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='enrollmentapplication',
            name='education_background',
            field=models.TextField(default='School Name, Grades, Final Year Attended'),
        ),
        migrations.AddField(
            model_name='enrollmentapplication',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], default='Male', max_length=20),
        ),
        migrations.AddField(
            model_name='enrollmentapplication',
            name='highest_qualification',
            field=models.CharField(default='e.g., Grade 12 Certificate, etc', max_length=200),
        ),
        migrations.AddField(
            model_name='enrollmentapplication',
            name='identity_document',
            field=cloudinary.models.CloudinaryField(default='NRC', max_length=255, verbose_name='identity_document'),
        ),
        migrations.AddField(
            model_name='enrollmentapplication',
            name='identity_number',
            field=models.CharField(default='010101/10/1', max_length=50),
        ),
        migrations.AddField(
            model_name='enrollmentapplication',
            name='identity_type',
            field=models.CharField(choices=[('national_id', 'National ID'), ('passport', 'Passport')], default='National ID', max_length=20),
        ),
        migrations.AddField(
            model_name='enrollmentapplication',
            name='next_of_kin_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='enrollmentapplication',
            name='next_of_kin_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='enrollmentapplication',
            name='next_of_kin_relationship',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enrollmentapplication',
            name='secondary_results',
            field=cloudinary.models.CloudinaryField(blank=True, default='Results', max_length=255, verbose_name='secondary_results'),
        ),
    ]
