# Generated by Django 5.2.5 on 2025-08-19 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contactmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollmentapplication',
            name='applied_at',
        ),
        migrations.AddField(
            model_name='enrollmentapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
