# Generated by Django 5.2.5 on 2025-08-19 03:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_enrollmentapplication_applied_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentapplication',
            name='applied_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
