# Generated by Django 5.2.5 on 2025-11-14 02:17

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_school_name_alter_department_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutSection',
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('short_certificate', 'Short Certificate Course'), ('diploma', 'Diploma Course')], default='diploma', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='enrollmentapplication',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], default='male', max_length=20),
        ),
        migrations.AlterField(
            model_name='enrollmentapplication',
            name='identity_document',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='identity_document'),
        ),
        migrations.AlterField(
            model_name='enrollmentapplication',
            name='identity_type',
            field=models.CharField(choices=[('national_id', 'National ID'), ('passport', 'Passport')], default='national_id', max_length=20),
        ),
        migrations.AlterField(
            model_name='enrollmentapplication',
            name='secondary_results',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='secondary_results'),
        ),
    ]
