# Generated by Django 5.1.1 on 2025-11-14 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_delete_aboutsection_alter_course_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='email',
            field=models.EmailField(default='info@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone',
            field=models.CharField(default='0000000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(default='email@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(default='No message provided.'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(default='Anonymous', max_length=200),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(default='No Subject', max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(default='No description provided.'),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(default='Not specified', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(default='Untitled Course', max_length=200),
        ),
        migrations.AlterField(
            model_name='enrollmentapplication',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.course'),
        ),
        migrations.AlterField(
            model_name='enrollmentapplication',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enrollmentapplication',
            name='email',
            field=models.EmailField(default='email@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='enrollmentapplication',
            name='full_name',
            field=models.CharField(default='Full Name', max_length=200),
        ),
        migrations.AlterField(
            model_name='enrollmentapplication',
            name='highest_qualification',
            field=models.CharField(default='Grade 12 Certificate', max_length=200),
        ),
        migrations.AlterField(
            model_name='enrollmentapplication',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='enrollmentapplication',
            name='phone',
            field=models.CharField(default='0000000000', max_length=20),
        ),
    ]
