# Generated by Django 5.2.5 on 2025-08-19 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0004_alter_assignment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='student_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
