# Generated by Django 5.2.5 on 2025-08-31 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0005_studentprofile_student_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='file',
            field=models.URLField(blank=True, null=True),
        ),
    ]
