# Generated by Django 5.2.5 on 2025-09-02 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0006_alter_assignment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='file_public_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
