# Generated by Django 5.2.5 on 2025-09-02 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_school_department'),
        ('student_portal', '0007_assignment_file_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.school'),
        ),
    ]
