# Generated by Django 5.2.5 on 2025-09-03 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_school_name_alter_department_unique_together'),
        ('student_portal', '0008_studentprofile_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.school'),
        ),
    ]
