# Generated by Django 5.2.5 on 2025-09-08 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0009_alter_studentprofile_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmaterial',
            name='video_url',
            field=models.URLField(blank=True, help_text='Paste a YouTube link for videos', null=True),
        ),
    ]
