# Generated by Django 5.2.5 on 2025-09-08 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0010_learningmaterial_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='score',
            field=models.PositiveIntegerField(blank=True, help_text='Score out of 100', null=True),
        ),
    ]
