# Generated by Django 5.2.5 on 2025-10-02 17:07

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_school_name_alter_department_unique_together'),
        ('instructor_portal', '0003_alter_instructorprofile_department'),
        ('student_portal', '0011_submission_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningmaterial',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('credits', models.PositiveIntegerField(default=3, help_text='Credit hours for the subject')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core.course')),
            ],
        ),
        migrations.AddField(
            model_name='announcement',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='student_portal.subject'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='student_portal.subject'),
        ),
        migrations.AddField(
            model_name='learningmaterial',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='student_portal.subject'),
        ),
        migrations.CreateModel(
            name='SemesterSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instructor_portal.instructorprofile')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_subjects', to='student_portal.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_instances', to='student_portal.subject')),
            ],
            options={
                'unique_together': {('semester', 'subject')},
            },
        ),
    ]
