# Generated by Django 5.2.5 on 2025-10-23 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_school_name_alter_department_unique_together'),
        ('instructor_portal', '0003_alter_instructorprofile_department'),
        ('student_portal', '0013_remove_announcement_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='courses',
            field=models.ManyToManyField(related_name='subjects', through='student_portal.CourseSubject', to='core.course'),
        ),
        migrations.AlterField(
            model_name='coursesubject',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instructor_portal.instructorprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='coursesubject',
            unique_together={('course', 'subject', 'semester')},
        ),
    ]
