# Generated by Django 5.2.5 on 2025-11-14 05:06

import cloudinary.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_contactinfo_address_alter_contactinfo_email_and_more'),
        ('student_portal', '0015_alter_announcement_options_alter_assignment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='course',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='course',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='learningmaterial',
            name='course',
        ),
        migrations.AddField(
            model_name='announcement',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='student_portal.subject'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='student_portal.subject'),
        ),
        migrations.AddField(
            model_name='learningmaterial',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_materials', to='student_portal.subject'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=models.TextField(default='No content provided.'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(default='Announcement', max_length=200),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.TextField(default='No description provided.'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='title',
            field=models.CharField(default='Untitled Assignment', max_length=200),
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='title',
            field=models.CharField(default='Untitled Material', max_length=200),
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='type',
            field=models.CharField(choices=[('outline', 'Subject Outline'), ('module', 'Module'), ('video', 'Video')], default='module', max_length=20),
        ),
        migrations.AlterField(
            model_name='semester',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.CharField(default='Semester', max_length=50),
        ),
        migrations.AlterField(
            model_name='semester',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='email',
            field=models.EmailField(default='student@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='full_name',
            field=models.CharField(default='Student Name', max_length=200),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(default='0000000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_pic'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(default='SUBJ000', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='subjects', through='student_portal.CourseSubject', to='core.course'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(default='Untitled Subject', max_length=200),
        ),
        migrations.CreateModel(
            name='SubjectEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('grade', models.CharField(blank=True, max_length=2)),
                ('final_score', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='student_portal.coursesubject')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_enrollments', to='student_portal.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('student', 'course_subject')},
            },
        ),
    ]
